#!/bin/bash

bspc monitor -d 1 2 3 4 5 6
bspc config border_width         1
bspc config window_gap           50
bspc config split_ratio          0.30
bspc config borderless_monocle	 true
bspc config gapless_monocle	 true
bspc config presel_feedback_color "#807e7e"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc rule -a "*:alacritty:cava" state=floating layer=above
config presel_feedback_color "#0d1117"
bspc config top_padding 25%
bspc config left_padding 25%
bspc config right_padding 25%
bspc config bot_padding 15%

$HOME/.config/bspwm/scripts/start.sh
